spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ikubinfo.car.rentals@gmail.com
    password: CWZHDWWYjS4pCiR
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

jwt:
  secret: javainuse

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

---
spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car-rental-testing
    username: postgres
    password: admin

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin